# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  GO_VERSION: 1.18

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      WORKINGDIR: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Log into registry 🐳
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

